services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_MYSQL_LOCALHOST_USER: true
    expose:
      - ${DB_PORT}
    volumes:
      - mysql:/var/lib/mysql:rw,Z
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - stack
      - radius

  privacyidea:
    image: gpappsoft/privacyidea-docker:${PI_VERSION}
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 3s
        window: 60s
    env_file:
      - ${ENVIRONMENT}
    expose:
      - ${PI_PORT}
    volumes:
      - pidata:/privacyidea/etc/persistent:rw,Z
      - type: bind
        source: scripts/
        target: /privacyidea/scripts/
        read_only: true
      - type: bind
        source: templates/resolver.json
        target: /privacyidea/etc/persistent/resolver.json
        read_only: true
    networks:
      - privacyidea
    healthcheck:
        test: [ "CMD", "/privacyidea/bin/healthcheck.py" ]
        start_period: 10s
        start_interval: 10s
        interval: 12s
        timeout: 10s
        retries: 6
    restart: always
    profiles:
      - fullstack
      - stack
      - radius

  reverse_proxy:
    image: nginx:stable-alpine
    environment:
      APP_PORT: ${PI_PORT}
      SERVERNAME: ${PROXY_SERVERNAME:-localhost}
    ports:
      - "${PROXY_PORT}:443"
    volumes:
      - type: bind
        source: ./templates/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./templates/pi.key
        target: /etc/nginx/ssl/pi.key
        read_only: true
      - type: bind
        source: ./templates/pi.pem
        target: /etc/nginx/ssl/pi.pem
        read_only: true
      - type: bind
        source: ./templates/nginx_default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: true
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - stack
      - radius

  freeradius:
    image: gpappsoft/privacyidea-freeradius:latest
    environment:
      RADIUS_PI_HOST: reverse_proxy
    ports:
      - "${RADIUS_PORT:-1812}:1812/tcp"
      - "${RADIUS_PORT:-1812}:1812/udp"
      - "${RADIUS_PORT_INC:-1813}:1813/udp"
    command:
      # uncomment the two lines below to debug radius
      #- freeradius
      #- -X
    volumes:
      - type: bind
        source: ./templates/clients.conf
        target: /etc/raddb/clients.conf
        read_only: true
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - radius

volumes:
  mysql: {}
  pidata: {}
 
networks:
  privacyidea: {}