---
- name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
  raw: systemctl disable --now {{ aptvar }}
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'
  loop_control:
    loop_var: aptvar
  tags: always

- name: Reload systemctl daemon to apply the new changes
  raw: systemctl daemon-reload
  tags: always

- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  tags: always

- name: Purge unattended upgrades
  raw: apt-get -y purge unattended-upgrades    
  tags: always

- name: Add Docke-CE key
  block:
    - name: Addign Docker repository key
      get_url:
        url:  https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/DockerCE.asc

    - name: Adding Docker-CE repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/DockerCE.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: dockerce
  tags: always
  
- name: Update Package Cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  tags: always

- name: Install basic OS tools 
  package:
    name: 
      - net-tools 
      - httpie 
      - vim
      - jq
      - rsync
      - gpg
      - uidmap
      - dbus-user-session
      - rootlesskit
    state: present
  tags: always

- name: Install Docker-CE
  package:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
  tags: always
