name: makeinstallpackage

on: 
  release:
    types: [prereleased,released]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v4
      - name: Compress action step
        run: tar cvzf privacyidea.tgz ./privacyidea
          
      - name: Add payload to install.sh
        id: add-payload
        run: cat install.sh privacyidea.tgz >> /install_pi.sh

      - uses: actions/upload-artifact@v4    
        with:
          name: install.sh
          path: /install_pi.sh
          compression-level: 0

    
